### ISSUE TITLE
ERROR:  this R is version 3.4.2, package 'omicsPrint' requires R >= 3.5

### ISSUE THREAD

**Issue by ewtobi** [molepi/omicsPrint#2]
Hi Maarten,

omicsPrint seems to give an error. It asks for R 3.5, while the newest version is just 3.4.3

best
elmar

**Comment by DavyCats** [comment]
Hey Elmar,

The package should function under R 3.4.2, however the bioconductor build system (which runs on a development version of R) gave a warning that the R dependency should be updated to R 3.5

If you want to install the package on R 3.4.2, you can clone the repository and edit the DESCRIPTION file by changing `Depends: R (>= 3.5)` to `Depends: R (>= 3.4)`.

You should then be able to install the package, eg. using `devtools::install()`.

Best regards,
Davy

**Comment by DavyCats** [comment]
I'm guessing this is resolved, than.

**Comment by ewtobi** [comment]
@DavyCats , Sorry I already got some tips from @mvaniterson 
I was able to install. Thanks

**Comment by swvanderlaan** [comment]
@ewtobi which tips did you get? I'm loading `OmicsPrint` directly from R using `install_github("molepi/omicsPrint")`. How should I change that to make it work? 

@DavyCats and @mvaniterson are you going to edit the code to make it work with R 3.4.x?

**Comment by DavyCats** [comment]
@swvanderlaan I made a new branch which specifies R3.4, rather than R3.5. To install you can use the following: `install_github("molepi/omicsPrint", ref="R3.4")`
