### ISSUE TITLE
Swaps function does not handle NA's

### ISSUE THREAD

**Issue by pjhop** [molepi/omicsPrint#5]
Hi,

I encountered this error when running the `alleleSharing` function when using a SNP-matrix that contains NAs:
`Error in if (swaps[i]) { : missing value where TRUE/FALSE needed`

Would be great if the function is able to handle missing values !

Best,
Paul

**Comment by DavyCats** [comment]
Hey Paul,

This should be fixed now, thanks for reporting!

Best regards,
Davy
